---
title: "ERP Visualization"
output: 
  html_document

---

<!-- Set general settings -->

```{r setup, include = FALSE}

# Set general settings for markdown file
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  comment = "",
  results = "hold"
)


# Clear environment
rm(list = ls())


# Enable/disable caching of time-consuming code chunks
knitr_cache_enabled = TRUE


# Load packages
library(dplyr)      # for data manipulation
library(ggplot2)    # for plotting
library(cowplot)    # for arranging plots
library(purrr)      # for calculate within-participant CIs for ERP trajectories
library(eegUtils)   # for plotting topographies
library(tidyr)      # for gather function 


# Load functions
source("./functions/summarySEwithinO.R")  # Function provided by R-cookbook: http://www.cookbook-r.com/Graphs/Plotting_means_and_error_bars_(ggplot2)/


# Set figure theme and colors
my_figure_theme <- theme_classic(base_size = 11) +
  theme(legend.position = "bottom", 
        strip.background = element_rect(fill="grey95", linetype = "blank"),
        plot.title = element_text(hjust = 0.5),
        panel.border = element_rect(colour = "grey", fill=NA, size=.5), 
        panel.grid.major.y = element_line(colour = "grey90", linetype = "dotted", size=0.3))
        

# instad of theme_classic: + theme_apa(base_size = 11)

my_figure_colors_1 <- c("steelblue1","lightcoral","blue","red")
my_figure_colors_2 <- c("seagreen1","lightsalmon","seagreen","lightsalmon4")
```

<!-- Load and clean data -->

```{r load-and-clean-data}

# Load data
resp_locked_data <- read.csv(file = "./data/response_locked_data_for_plots.csv", header = TRUE)


# Rename conditions
resp_locked_data$condition[resp_locked_data$condition == 1] <- "correct";
resp_locked_data$condition[resp_locked_data$condition == 2] <- "incorrect";



# Add stimulation condition variable
resp_locked_data$stimulation <- NA
resp_locked_data[
  resp_locked_data$participant_id =="C_01_T1"| resp_locked_data$participant_id =="C_02_T1"| resp_locked_data$participant_id =="C_03_T2"|
  resp_locked_data$participant_id =="C_04_T2"| resp_locked_data$participant_id =="C_05_T1"| resp_locked_data$participant_id =="C_06_T2"|
  resp_locked_data$participant_id =="C_07_T1"| resp_locked_data$participant_id =="C_08_T1"| resp_locked_data$participant_id =="C_09_T2"|
  resp_locked_data$participant_id =="C_10_T2"| resp_locked_data$participant_id =="C_11_T2"| resp_locked_data$participant_id =="C_12_T2"|
  resp_locked_data$participant_id =="C_13_T1"| resp_locked_data$participant_id =="C_15_T2"| resp_locked_data$participant_id =="C_16_T1"|
  resp_locked_data$participant_id =="C_17_T2"| resp_locked_data$participant_id =="C_18_T2"| resp_locked_data$participant_id =="C_19_T1"|
  resp_locked_data$participant_id =="C_20_T1"| resp_locked_data$participant_id =="C_21_T2"| resp_locked_data$participant_id =="C_22_T2"|
  resp_locked_data$participant_id =="C_23_T1"| resp_locked_data$participant_id =="C_24_T1"| resp_locked_data$participant_id =="C_25_T1"|
  resp_locked_data$participant_id =="C_26_T1"| resp_locked_data$participant_id =="C_27_T2"| resp_locked_data$participant_id =="C_28_T2"|
  resp_locked_data$participant_id =="C_29_T1"| resp_locked_data$participant_id =="C_30_T2"| resp_locked_data$participant_id =="P_01_T1"|
  resp_locked_data$participant_id =="P_02_T2"| resp_locked_data$participant_id =="P_03_T2"| resp_locked_data$participant_id =="P_04_T1"|
  resp_locked_data$participant_id =="P_05_T1"| resp_locked_data$participant_id =="P_06_T1"| resp_locked_data$participant_id =="P_07_T2"|
  resp_locked_data$participant_id =="P_08_T2"| resp_locked_data$participant_id =="P_09_T2"| resp_locked_data$participant_id =="P_10_T1"|
  resp_locked_data$participant_id =="P_11_T2"| resp_locked_data$participant_id =="P_12_T2"| resp_locked_data$participant_id =="P_13_T1"|
  resp_locked_data$participant_id =="P_15_T1"| resp_locked_data$participant_id =="P_16_T1"| resp_locked_data$participant_id =="P_17_T2"|
  resp_locked_data$participant_id =="P_18_T1"| resp_locked_data$participant_id =="P_19_T1"| resp_locked_data$participant_id =="P_20_T2"|
  resp_locked_data$participant_id =="P_21_T2"| resp_locked_data$participant_id =="P_22_T1"| resp_locked_data$participant_id =="P_23_T1"|
  resp_locked_data$participant_id =="P_24_T2"| resp_locked_data$participant_id =="P_25_T1"| resp_locked_data$participant_id =="P_26_T2"|
  resp_locked_data$participant_id =="P_27_T1"| resp_locked_data$participant_id =="P_28_T2"| resp_locked_data$participant_id =="P_29_T2"|
  resp_locked_data$participant_id =="P_30_T1",]$stimulation <- "sham"

resp_locked_data[
  resp_locked_data$participant_id =="C_01_T2"| resp_locked_data$participant_id =="C_02_T2"| resp_locked_data$participant_id =="C_03_T1"|
  resp_locked_data$participant_id =="C_04_T1"| resp_locked_data$participant_id =="C_05_T2"| resp_locked_data$participant_id =="C_06_T1"|
  resp_locked_data$participant_id =="C_07_T2"| resp_locked_data$participant_id =="C_08_T2"| resp_locked_data$participant_id =="C_09_T1"|
  resp_locked_data$participant_id =="C_10_T1"| resp_locked_data$participant_id =="C_11_T1"| resp_locked_data$participant_id =="C_12_T1"|
  resp_locked_data$participant_id =="C_13_T2"| resp_locked_data$participant_id =="C_15_T1"| resp_locked_data$participant_id =="C_16_T2"|
  resp_locked_data$participant_id =="C_17_T1"| resp_locked_data$participant_id =="C_18_T1"| resp_locked_data$participant_id =="C_19_T2"|
  resp_locked_data$participant_id =="C_20_T2"| resp_locked_data$participant_id =="C_21_T1"| resp_locked_data$participant_id =="C_22_T1"|
  resp_locked_data$participant_id =="C_23_T2"| resp_locked_data$participant_id =="C_24_T2"| resp_locked_data$participant_id =="C_25_T2"|
  resp_locked_data$participant_id =="C_26_T2"| resp_locked_data$participant_id =="C_27_T1"| resp_locked_data$participant_id =="C_28_T1"|
  resp_locked_data$participant_id =="C_29_T2"| resp_locked_data$participant_id =="C_30_T1"| resp_locked_data$participant_id =="P_01_T2"|
  resp_locked_data$participant_id =="P_02_T1"| resp_locked_data$participant_id =="P_03_T1"| resp_locked_data$participant_id =="P_04_T2"|
  resp_locked_data$participant_id =="P_05_T2"| resp_locked_data$participant_id =="P_06_T2"| resp_locked_data$participant_id =="P_07_T1"|
  resp_locked_data$participant_id =="P_08_T1"| resp_locked_data$participant_id =="P_09_T1"| resp_locked_data$participant_id =="P_10_T2"|
  resp_locked_data$participant_id =="P_11_T1"| resp_locked_data$participant_id =="P_12_T1"| resp_locked_data$participant_id =="P_13_T2"|
  resp_locked_data$participant_id =="P_15_T2"| resp_locked_data$participant_id =="P_16_T2"| resp_locked_data$participant_id =="P_17_T1"|
  resp_locked_data$participant_id =="P_18_T2"| resp_locked_data$participant_id =="P_19_T2"| resp_locked_data$participant_id =="P_20_T1"|
  resp_locked_data$participant_id =="P_21_T1"| resp_locked_data$participant_id =="P_22_T2"| resp_locked_data$participant_id =="P_23_T2"|
  resp_locked_data$participant_id =="P_24_T1"| resp_locked_data$participant_id =="P_25_T2"| resp_locked_data$participant_id =="P_26_T1"|
  resp_locked_data$participant_id =="P_27_T2"| resp_locked_data$participant_id =="P_28_T1"| resp_locked_data$participant_id =="P_29_T1"|
  resp_locked_data$participant_id =="P_30_T2",]$stimulation <- "verum"



# Add group and session variables and remove string '_T1/T2' from participant ID (to get correct number of factor levels later); make all factors
resp_locked_data <- resp_locked_data  %>% 
  dplyr::mutate(
    group          = as.factor(ifelse(substr(participant_id, 1,1) == "C", "HC", "OCD")),
    session        = as.factor(ifelse(substr(participant_id, 6,7) == "T1", "T1", "T2")),
    participant_id = as.factor(substr(participant_id, 1,4)), 
    condition      = as.factor(condition),
    stimulation    = as.factor(stimulation)
    )


# Exclude P_02 (due to retainer) and C_02 (as preregistered: patients are excluded with their match)
resp_locked_data <- resp_locked_data[resp_locked_data$participant_id != "P_02" & resp_locked_data$participant_id != "C_02",]
resp_locked_data$participant_id <- droplevels(resp_locked_data$participant_id)
```

## ERP Trajectories {.tabset}
***

### Per participant

```{r plot-per-participant, fig.height = 9, fig.width = 10, cache = knitr_cache_enabled}
# Plot ERPs per participant for HC
plot_per_participant_HC <- ggplot(resp_locked_data[resp_locked_data$group == "HC",],aes(time, FCz)) +
  stat_summary(fun = mean, geom = "line", size = 0.5, linetype = "solid", aes(colour = stimulation:condition)) +
  geom_vline(xintercept = 0, linetype = "dashed", colour="grey" ) +
  geom_hline(yintercept = 0, linetype = "dashed", colour="grey") +  
  geom_ribbon(aes(xmin=0, xmax=100), alpha=.2, fill="grey70") +
  coord_cartesian(ylim=c(-15, 15), xlim=c(-500,600)) +
  scale_y_continuous(breaks=seq(-15, 15, 10)) +
  scale_x_continuous(breaks=c(-200, 100, 400)) +
  scale_colour_manual(values = my_figure_colors_2) +  
  facet_wrap(.~ participant_id+session, ncol = 8, labeller = labeller(.multi_line = FALSE, sep=": ")) +
  ggtitle("ERPs per participant: HC") +  
  labs(x = "\ntime (ms)", y = expression(paste("Mean amplitude at FCz [",mu,"V]")), colour = "") +  
  theme(strip.text.x = element_text(margin = margin(0, 0, 0, 0))) +
  my_figure_theme


# Save plot
ggsave("./figures/figure_ERPs_per_participant_HC.tiff", width = 36, height = 26, units = "cm", dpi=600, compression = "lzw")


# Display plot
plot_per_participant_HC


# Plot ERPs per participant for OCD
plot_per_participant_OCD <- ggplot(resp_locked_data[resp_locked_data$group == "OCD",],aes(time, FCz)) +
  stat_summary(fun = mean, geom = "line", size = 0.5, linetype = "solid", aes(colour = stimulation:condition)) +
  geom_vline(xintercept = 0, linetype = "dashed", colour="grey" ) +
  geom_hline(yintercept = 0, linetype = "dashed", colour="grey") +  
  geom_ribbon(aes(xmin=0, xmax=100), alpha=.2, fill="grey70") +
  coord_cartesian(ylim=c(-15, 15), xlim=c(-500,600)) +
  scale_y_continuous(breaks=seq(-15, 15, 10)) +
  scale_x_continuous(breaks=c(-200, 100, 400)) +
  scale_colour_manual(values = my_figure_colors_2) +  
  facet_wrap(.~ participant_id+session, ncol = 8, labeller = labeller(.multi_line = FALSE, sep=": ")) +
  ggtitle("ERPs per participant: OCD") +  
  labs(x = "\ntime (ms)", y = expression(paste("Mean amplitude at FCz [",mu,"V]")), colour = "") +  
  theme(strip.text.x = element_text(margin = margin(0, 0, 0, 0))) +
  my_figure_theme


# Save plot
ggsave("./figures/figure_ERPs_per_participant_OCD.tiff", width = 36, height = 26, units = "cm", dpi=600, compression = "lzw")


# Display plot
plot_per_participant_OCD
```
<br><br>

### ERPs as a function of group and stimulation {.active}

```{r plot-group-by-stimulation, fig.height = 10, fig.width = 10, dpi=600, fig.cap = "Note. Response-locked ERP trajectories (mean amplitude at FCz from 0 to 100 ms) as a function of (A) stimulation by group and (B) group by stimulation. Shaded areas represent 95% CIs and are adjusted for within-participant designs as described by Morey (2008).", cache = knitr_cache_enabled}

# Calculate running within-participant CIs
running_CIs_group_stim <- resp_locked_data %>%
  split(.$time) %>%
  map(~summarySEwithinO(data = .,
                       measurevar = "FCz",
                       withinvars = c("condition", "stimulation"),
                       betweenvars = "group",
                       idvar = "participant_id"))


# Calculate running within-participant CIs 
CIs_group_stim <- purrr::map_df(running_CIs_group_stim,magrittr::extract) %>%
  dplyr::mutate(
    time = rep(unique(resp_locked_data$time), each = 8) # Note: 8 refers to the number of conditions (group x stimulation x response_type = 2 x 2 x 2 = 8)
    )


# Plot ERPs per stimulation by group
plot_stim_by_group <- ggplot(resp_locked_data,aes(time, FCz)) +
  stat_summary(fun = mean, geom = "line", size = 0.5, linetype = "solid", aes(colour= stimulation:condition)) +
  geom_ribbon(data = CIs_group_stim, aes(ymin = FCz-ci, ymax = FCz+ci, fill = stimulation:condition), alpha = 0.15) + guides(fill = "none") +
  geom_vline(xintercept = 0, linetype = "dashed", colour="grey" ) +
  geom_hline(yintercept = 0, linetype = "dashed", colour="grey") +  
  geom_ribbon(aes(xmin=0, xmax=100), alpha=.2, fill="grey70") +
  coord_cartesian(ylim=c(-10,10), xlim=c(-500,1000)) +
  scale_y_continuous(breaks=seq(-10,10,2)) +
  scale_x_continuous(breaks=seq(-500,1000,200)) +
  scale_colour_manual(values = my_figure_colors_2) +
  scale_fill_manual(values = my_figure_colors_2) +
  facet_grid(. ~ group) + 
  ggtitle("ERPs per stimulation by group") +
  labs(x = "\ntime (ms)", y = expression(paste("Mean amplitude at FCz [",mu,"V]")), colour = "") +
  my_figure_theme


# Plot ERPs per group by stimulation
plot_group_by_stim <- ggplot(resp_locked_data,aes(time, FCz)) +
  stat_summary(fun = mean, geom = "line", size = 0.5, linetype = "solid", aes(colour= group:condition)) +
  geom_ribbon(data = CIs_group_stim, aes(ymin = FCz-ci, ymax = FCz+ci, fill = group:condition), alpha = 0.15) + guides(fill = "none") +
  geom_vline(xintercept = 0, linetype = "dashed", colour="grey" ) +
  geom_hline(yintercept = 0, linetype = "dashed", colour="grey") + 
  geom_ribbon(aes(xmin=0, xmax=100), alpha=.2, fill="grey70") +
  coord_cartesian(ylim=c(-10,10), xlim=c(-500,1000)) +
  scale_y_continuous(breaks=seq(-10,10,2)) +
  scale_x_continuous(breaks=seq(-500,1000,200)) +
  scale_colour_manual(values = my_figure_colors_1) +
  scale_fill_manual(values = my_figure_colors_1) +
  facet_grid(. ~ stimulation) + 
  ggtitle("ERPs per group by stimulation") +
  labs(x = "\ntime (ms)", y = expression(paste("Mean amplitude at FCz [",mu,"V]")), colour = "") +
  my_figure_theme 


# Arrange plots
figure_ERP_trajectories <- ggdraw() +
  draw_plot(plot_stim_by_group,  x = 0, y =.5, width = 1, height =.5) +
  draw_plot(plot_group_by_stim,  x = 0, y = 0, width = 1, height =.5) +
  draw_plot_label(c("A", "B"), c(0, 0), c(1, .5), size = 15)


# Save plot
ggsave("./figures/figure_ERP_trajectories.tiff", width = 14, height = 18, units = "cm", dpi=600, compression = "lzw")


# Display plot
figure_ERP_trajectories
```
<br>
*Note: CRN is clearly visible but positive. This is quite typical for mastoid reference. *
<br><br>

## ERP Topographies {.tabset}
***

### Per group and response type

```{r topographies, fig.height = 7, fig.width = 10, dpi=600, fig.cap = "Note. Response-locked ERP topograhpies (from 0 to 100 ms) separately for both groups and response conditions.", cache = knitr_cache_enabled}
# Convert to long format for electrodes
data_topo <- resp_locked_data %>%
  # Remove channels of no interest
  dplyr::select(-IO1, -M1, -F9, -F10) %>%
  # Change from wide to long format for electrodes
  tidyr::gather(., electrode, amplitude, Fp1:O2, factor_key = TRUE)  %>%
  # Select time windows
  dplyr::filter(time >= 0 & time <= 100) %>%
  # Add electrode information
  electrode_locations(., electrode = "electrode", drop = FALSE, montage = NULL)


# Calculate difference score incorrect-correct
data_topo_diff <- left_join(data_topo[data_topo$condition == "correct",], data_topo[data_topo$condition == "incorrect",], by = c("participant_id", "time", "group","session","stimulation","electrode")) %>%
  # Calculate incorrect - correct
  dplyr::mutate(amplitude = amplitude.y - amplitude.x) %>%
  # Remove unncessary columns
  dplyr::select(-c(condition.x, condition.y, amplitude.x, amplitude.y)) %>%
  # Select time windows
  dplyr::filter(time >= 0 & time <= 100) %>%
  # Add electrode information
  electrode_locations(., electrode = "electrode", drop = FALSE, montage = NULL)


# Calculate difference score sham-verum
data_topo_diff_stimulation <- left_join(data_topo[data_topo$stimulation == "verum",], data_topo[data_topo$stimulation == "sham",], by = c("participant_id", "time", "group","condition","electrode")) %>%
  # Calculate sham - verum
  dplyr::mutate(amplitude = amplitude.y - amplitude.x) %>%
  # Remove unncessary columns
  dplyr::select(-c(stimulation.x, stimulation.y, amplitude.x, amplitude.y)) %>%
  # Select time windows
  dplyr::filter(time >= 0 & time <= 100) %>%
  # Add electrode information
  electrode_locations(., electrode = "electrode", drop = FALSE, montage = NULL)


# Draw topographies
plot_topo <- ggplot(data_topo, aes(x = x, y = y, fill = amplitude, label = electrode)) + 
    geom_topo(grid_res = 300, interp_limit = "head", chan_markers = "point", chan_size = 0.5, head_size = 0.9) + 
    scale_fill_distiller(palette = "RdBu", limits = c(-5, 12)) + 
    theme_void() + 
    coord_equal() + 
    labs(fill = expression(paste(mu, "V"))) + 
    theme(strip.text = element_text(size = 12, hjust = .5, face = "bold"),legend.position = "bottom") + 
    facet_grid(cols = vars(condition), rows = vars(group), switch = "y") +
    theme(strip.text.y.left = element_text(angle = 0)) # to show group labels horizontally


plot_topo_diff <- ggplot(data_topo_diff, aes(x = x, y = y, fill = amplitude, label = electrode)) + 
    geom_topo(grid_res = 300, interp_limit = "head", chan_markers = "point", chan_size = 0.5, head_size = 0.9) + 
    scale_fill_distiller(palette = "RdBu", limits = c(-12, 0)) + 
    theme_void() + 
    coord_equal() + 
    ggtitle("incorrect-correct") +
    labs(fill = expression(paste(mu, "V"))) + 
    theme(plot.title = element_text(size = 12, hjust = .5, face = "bold"),legend.position = "bottom") + 
    facet_grid(rows = vars(group)) +
    theme(strip.text.y = element_blank())  # remove facet labels

    
# Store legends separately in order to center them correctly
legend_topo      <- get_legend(plot_topo)
legend_topo_diff <- get_legend(plot_topo_diff)


# Remove previous legends from plots 
plot_topo       <- plot_topo      + theme(legend.position = "none")
plot_topo_diff  <- plot_topo_diff + theme(legend.position = "none")


# Arrange plots
figure_ERP_topographies <- ggdraw() +
  draw_plot(plot_topo,        x =  0,  y =  .1, width = .66,  height = .90)+
  draw_plot(plot_topo_diff,   x = .66, y =  .1, width = .306, height = .90)+
  draw_plot(legend_topo,      x = .23, y =  0,  width = .2,   height = .1) + 
  draw_plot(legend_topo_diff, x = .7,  y =  0,  width = .2,   height = .1)


# Save plot
ggsave("./figures/figure_ERP_topographies.tiff", width = 16, height = 10, units = "cm", dpi=600, compression = "lzw")


# Display plot
figure_ERP_topographies
```
<br><br>

### Per group, response type, and stimulation

```{r topographies-stimulation, fig.height = 7, fig.width = 12, dpi=600, fig.cap = "Note. Response-locked ERP topograhpies (from 0 to 100 ms) separately for both groups, response conditions, and stimulation conditions.", cache = knitr_cache_enabled}

# Draw topographies including stimulation
plot_topo_stimulation <- plot_topo + 
  facet_grid(cols = vars(condition, stimulation), rows = vars(group), switch = "y") +
  scale_fill_distiller(palette = "RdBu", limits = c(-6, 12)) + 
  theme(legend.position = "bottom") 


plot_topo_diff_stimulation <- ggplot(data_topo_diff_stimulation, aes(x = x, y = y, fill = amplitude, label = electrode)) + 
    geom_topo(grid_res = 300, interp_limit = "head", chan_markers = "point", chan_size = 0.5, head_size = 0.9) + 
    scale_fill_distiller(palette = "RdBu", limits = c(-2, 2)) + 
    theme_void() + 
    coord_equal() + 
    ggtitle("sham-verum") +
    labs(fill = expression(paste(mu, "V"))) + 
    theme(plot.title = element_text(size = 12, vjust = 3, hjust = .5, face = "bold"),legend.position = "bottom") + 
    facet_grid(cols = vars(condition), rows = vars(group)) +
    theme(strip.text.y = element_blank())  # remove facet labels



# Store legends separately in order to center them correctly
legend_topo_stimulation      <- get_legend(plot_topo_stimulation)
legend_topo_diff_stimulation <- get_legend(plot_topo_diff_stimulation)


# Remove previous legends from plots 
plot_topo_stimulation       <- plot_topo_stimulation      + theme(legend.position = "none")
plot_topo_diff_stimulation  <- plot_topo_diff_stimulation + theme(legend.position = "none")


# Arrange plots
figure_ERP_topographies_stimulation <- ggdraw() +
  draw_plot(plot_topo_stimulation,        x =  0,  y =  0,   width = .66,  height = .95)+
  draw_plot(plot_topo_diff_stimulation,   x = .67, y =  0,   width = .306, height = .95)+
  draw_plot(legend_topo_stimulation,      x = .23, y =  .08, width = .2,   height = .1) + 
  draw_plot(legend_topo_diff_stimulation, x = .7,  y =  .08, width = .2,   height = .1)



# Save plot
ggsave("./figures/figure_ERP_topographies_stimulation.tiff", width = 20, height = 14, units = "cm", dpi=600, compression = "lzw")


# Display plot
figure_ERP_topographies_stimulation
```

